// <auto-generated />
namespace CommunityConnections.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class nameaddedinads : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nameaddedinads));
        
        string IMigrationMetadata.Id
        {
            get { return "202205170853452_nameaddedinads"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
